default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: agustin
  password: 123456

development:
  <<: *default
  database: vitawallet_development

 
test:
  <<: *default
  database: vitawallet_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
  pool: 5
  timeout: 5000